### ISSUE TITLE
Change activity item markers for in-game

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#115] opened 2017-05-22 08:36 UTC
When having different kinds of activity items on the same map, some of them was harder for users to understand.

The standard question (the check mark), was for example seen as some kind of goal. I don't think there is any reason why the player must know what kind of question it is before pressing.

I propose that all markers, besides information, should be given a question mark icon:
![question marker mock up](https://cloud.githubusercontent.com/assets/26867575/26298945/542cfa38-3ed9-11e7-90e6-4eb3643b5e04.png)

The different markers could be kept as a viewing option for when editing an activity.

**Comment by pjotrsavitski** [comment] 2017-05-22 10:51
@tammets @kaimikael @tirts This is not my decision to make. Any thoughts on the topic?

**Comment by kaimikael** [comment] 2017-05-22 11:32
I support this.  The players don't have any particular advantage in having a multitude of different icons that invite interpretation, they might possibly be of use to an activity designer, but that is an issue that would have to be separately tested.

**Comment by pjotrsavitski** [comment] 2017-06-05 18:49
This one seems to be a duplicate of #118 

Closing the issue as the icons have already been changed.

**Closed by pjotrsavitski** 2017-06-05 18:49 UTC
Labels: question
