### ISSUE TITLE
"Language" and "Location" hinders saving changes to Act. Item 

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#162] opened 2017-11-02 09:01 UTC
When trying to save changes to an Activity Item, the "Language" and "Location" fields are
The Language field does not accept "Swedish".  Any other option seem to work. This was also issue when using the site in Swedish and trying the change the language to "Swedish".

When trying to change an Item created by someone else, Location is locked and somehow causes issues. This makes it not possible to edit someone else's Item.

![skarmklipp](https://user-images.githubusercontent.com/26867575/32317172-2c491ed8-bfb3-11e7-9384-8e4d1e53e1b1.PNG)

**Comment by pjotrsavitski** [comment] 2017-11-02 09:26
The language field not accepting Swedish is surely a bug as it should not be like that.

Changing interface language to Swedish worked for me. I would assume you are referring to the same issue, changing the language to Swedish while having that as the interface language. The interface language has no affect on that kind of things, it just determines the translations used for the texts.

The location being locked is a feature. This is to protect that from someone else making the change (administrators are not affected). It has to do with permission system and the fact that roles specific to certain Zoo are only granted extended privileges to the objects that are related to that Zoo. Changing that would remove the ability of editing altogether.

I will also deal with the issues being caused by that, this has to do with the validator expecting the value and not getting any (disabled elements are not being submitted).

It should be fixed today, but the change could arrive to the server once all the other changes are tested out (will see about that).

**Closed** 2017-11-02 13:22 UTC
Labels: bug, high priority
