### ISSUE TITLE
Explain how to turn on geolocation

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#103] opened 2017-05-12 15:50 UTC
As a player I need to understand how to turn on geolocation on my device.

On an iPhone, for example, allowing geolocation in web browser is a multi-step process.  If the client detects that geolocation is not available it can, based on its knowledge of the OS it is running on, display an animation or other explanation of how to turn on geolocation on this specific device.  (Note that an animation has to be created for all supported languages as well!)
@PatriciaMoller is working on a sketch of this.

**Comment by pjotrsavitski** [comment] 2017-05-15 10:05
The status code can be detected. Will wait until the visuals are decided on and complete.

**Comment by pjotrsavitski** [comment] 2017-08-21 12:06
This one is duplicate of #117 
I'll close this one and any remaining work should be done in that issue.

**Closed by pjotrsavitski** 2017-08-21 12:06 UTC
